$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot
$bank=Get-Content (Join-Path $root 'data/card-questions.json') -Raw -Encoding UTF8|ConvertFrom-Json
$forms=Get-Content (Join-Path $root 'data/mock-exams.json') -Raw -Encoding UTF8|ConvertFrom-Json
$overrides=Get-Content (Join-Path $root 'data/distractor-overrides.json') -Raw -Encoding UTF8|ConvertFrom-Json
$errors=[System.Collections.Generic.List[string]]::new();$byId=@{};foreach($q in $bank){$byId[$q.id]=$q}
if($bank.Count-lt120){$errors.Add("Bank has $($bank.Count); need 120.")};if($forms.Count-ne2){$errors.Add("Need two forms.")}
if($overrides.Count-ne$bank.Count-or@($overrides.id|Sort-Object -Unique).Count-ne$bank.Count){$errors.Add('Distractor overrides must map one-to-one to generated questions.')}
foreach($override in $overrides){if($override.review.status-ne'approved'-or!$override.review.method-or!$override.review.date){$errors.Add("Incomplete review evidence for $($override.id)")}}
$ranges=@{I=@(9,15);II=@(9,15);III=@(7,10);IV=@(4,7);V=@(21,27)}
foreach($form in $forms){if($form.questionIds.Count-ne60){$errors.Add("Form $($form.id) not 60.")};if(@($form.questionIds|Sort-Object -Unique).Count-ne60){$errors.Add("Form $($form.id) has duplicates.")};if($form.status-ne'release-reviewed'){$errors.Add("Form $($form.id) is not release-reviewed.")};$counts=@{};foreach($id in $form.questionIds){if(!$byId.ContainsKey($id)){$errors.Add("Missing $id");continue};$q=$byId[$id];$counts[$q.area]=1+[int]$counts[$q.area];if($q.choices.Count-ne4-or@($q.choices|Sort-Object -Unique).Count-ne4){$errors.Add("Bad choices $id")};if(!$q.explanation-or$q.citations.Count-lt1){$errors.Add("Missing rationale/citation $id")}};foreach($a in $ranges.Keys){$n=[int]$counts[$a];if($n-lt$ranges[$a][0]-or$n-gt$ranges[$a][1]){$errors.Add("Form $($form.id) Area $a=$n outside range")}}}
$unreviewed=@($bank|Where-Object distractorReview -ne 'approved')
foreach($q in $bank){if($q.citations.Count-lt2-or@($q.citations|Where-Object label -ne 'FAA-S-ACS-10B').Count-lt1){$errors.Add("Missing rule/guidance citation for $($q.id)")}}
foreach($form in $forms){$doc=Join-Path $root "study/mock-exam-$($form.id.ToLowerInvariant()).md";if(!(Test-Path $doc)){$errors.Add("Missing printable form $doc");continue};$text=Get-Content $doc -Raw -Encoding UTF8;$parts=$text-split'(?m)^# Answer key and remediation\s*$';if($parts.Count-ne2){$errors.Add("Malformed answer-key boundary in $doc");continue};if(([regex]::Matches($parts[0],'(?m)^## \d+\. ')).Count-ne60){$errors.Add("Printable form $($form.id) does not contain 60 questions.")};if(([regex]::Matches($parts[1],'(?m)^## \d+\. [A-D] - UA\.')).Count-ne60){$errors.Add("Printable form $($form.id) does not contain 60 keyed ACS mappings.")};foreach($label in @('Rationale','Remediation','Source')){if(([regex]::Matches($parts[1],"(?m)^\*\*${label}:\*\*")).Count-ne60){$errors.Add("Printable form $($form.id) lacks 60 $label entries.")}}}
if($env:PART107_RELEASE_VALIDATE -eq '1' -and $unreviewed.Count){$errors.Add("$($unreviewed.Count) questions have unapproved distractors.")}
if($errors.Count){$errors|ForEach-Object{Write-Error $_};exit 1};Write-Output "PASS: $($bank.Count) questions and two 60-question forms meet structural and ACS distribution rules.";if($unreviewed.Count){Write-Warning "$($unreviewed.Count) questions remain blocked from release pending distractor review. Set PART107_RELEASE_VALIDATE=1 to enforce the gate."}
